spring:
  datasource:
    url: jdbc:mysql://host.docker.internal:3305/calculator
    username: root
    password: my-secret-pw
    #dialect: org.hibernate.dialect.MySQL8Dialect

  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    #disable liquibase at start-up
    enabled: false


server:
  port: 9003